TUSHARE_UNIVERSE_DAILY_SQL = """
    select
        trade_date,
        code,
        name as code_name,
        1 as security_type,
        1 as list_status,
        industry,
        area,
        pe,
        float_share,
        total_share,
        total_assets,
        liquid_assets,
        fixed_assets,
        reserved,
        reserved_pershare,
        eps,
        bvps,
        pb,
        list_date,
        undp,
        per_undp,
        rev_yoy,
        profit_yoy,
        gpr,
        npr,
        holder_num,
        is_st
    from tushare.stock_daily_technical
    where ts_code is not null
"""


TUSHARE_BAR_1D_QFQ_SQL = """
    select
        trade_date,
        code,
        qfq_open as open,
        qfq_high as high,
        qfq_low as low,
        qfq_close as close,
        qfq_pre_close as preclose,
        vol as volume,
        amount,
        cast(null as double) as turn,
        1 as tradestatus,
        pct_chg,
        is_st,
        atr_5,
        atr_14,
        atr_30,
        atr_pct_5,
        atr_pct_14,
        atr_pct_30,
        avg_volume_5,
        avg_volume_10,
        avg_volume_20,
        volume_ratio_5,
        volume_ratio_10,
        volume_ratio_20,
        vwap_5,
        vwap_14,
        vwap_20,
        vwap_30,
        ma_5,
        ma_10,
        ma_20,
        ma_30,
        ma_60,
        ma_120,
        bias_5,
        bias_10,
        bias_20,
        bias_30,
        bias_60,
        bias_120,
        ma_slope_5,
        ma_slope_10,
        ma_slope_20,
        ma_slope_30,
        ma_slope_60,
        ma_slope_120,
        er_10,
        er_20,
        er_60,
        boll_upper_10_2,
        boll_middle_10_2,
        boll_lower_10_2,
        boll_bandwidth_10_2,
        boll_percent_b_10_2,
        boll_upper_20_2,
        boll_middle_20_2,
        boll_lower_20_2,
        boll_bandwidth_20_2,
        boll_percent_b_20_2,
        boll_upper_60_2,
        boll_middle_60_2,
        boll_lower_60_2,
        boll_bandwidth_60_2,
        boll_percent_b_60_2,
        macd_dif_12_26_9,
        macd_dea_12_26_9,
        macd_hist_12_26_9,
        rsi_5,
        rsi_14,
        rsi_20,
        roc_5,
        roc_10,
        roc_20,
        roc_60,
        roc_120,
        kdj_k_9_3_3,
        kdj_d_9_3_3,
        kdj_j_9_3_3,
        body_atr14_ratio,
        range_atr14_ratio,
        body_range_ratio,
        upper_shadow_range_ratio,
        lower_shadow_range_ratio,
        overnight_return
    from tushare.stock_daily_technical
"""
